loadAllFunctions <- function() {
  source("functions/preprocessFunction.R")
  source("functions/plotFunctions.R")
  source("functions/generatePCA.R")
  source("functions/getVolumes.R")
  source("functions/clustering.R")
  source("functions/getVolumes.R")
  source("functions/generateSummaryText.R")
  source("functions/helpers.R")
  source("functions/doFitCurve.R")
  source("functions/infoStateMassageHandler.R")
  source("functions/fitCurveErrorHandler.R")
  source("functions/getStatistics.R")
  source("functions/dummyPlot.R")
  source("functions/downloadHandlers.R")
  source("functions/saveSettings.R")
  source("functions/createDataTable.R")
  source("functions/storeResults.R")
  source("functions/emptyAppDataObject.R")
  source("functions/detectOutliers.R")
  source("functions/handlePreprocSettings.R")
  source("functions/loadSpectraData.R")
  source("functions/selectDir.R")
}


